name: myfamily
description: project for dailty conversation of family

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  json_serializable: ^6.7.1
  build_runner:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  skeleton_text:

flutter:
  uses-material-design: true
  assets:
    - assets/

