name: myfamily
description: project for dailty conversation of family

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^5.0.0-release-candidate-5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  loading_indicator: ^3.1.1
  flutter_date_difference: ^1.0.1
  firebase_storage: ^11.5.3
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  skeleton_text:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/prev.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/locales/

